Update osbox

diff --git a/usr/sbin/osbox b/usr/sbin/osbox
--- a/usr/sbin/osbox
+++ b/usr/sbin/osbox
@@ -38,6 +38,7 @@ fi
 
 if [ "$1" == "reset" ]; then
   echo "0">$OSBOX_STATE_FILE
+  rm -f /etc/osbox/osbox.owner
   exit 0;
 fi
 if [ "$1" == "reinstall" ]; then
@@ -68,6 +69,18 @@ fi
 if [ "$1" == "network" ]; then
   bash /usr/lib/osbox/stage/network.sh $2 $3 $4 $5 $6
   exit 0;
+fi
+
+
+if [ "$1" == "reachablebydomainname" ]; then
+     if [ "$INSTALLSTATE" == "11" ]; then
+        echo "12">/etc/osbox/osbox.state
+        exit 0
+     else
+        echo "Invalid state."
+        exit 1
+     fi
+
 fi
 
 ######################################
@@ -107,8 +120,14 @@ generate_post_data()
 ######################################
 if [ "$1" == "owner" ]; then
     if [ "$2" == "set" ]; then
-        #bash /usr/share/blackbox/networkinfo.sh
-        echo "$3">/etc/osbox/osbox.owner
+        if [  "$(</etc/osbox/osbox.state)" == "12" ]; then
+            #bash /usr/share/blackbox/networkinfo.sh
+            echo "$3">/etc/osbox/osbox.owner
+            echo "13">/etc/osbox/osbox.state
+        else
+            echo "Wrong state!  $(</etc/osbox/osbox.state)";
+            exit 1
+        fi
     fi
     exit;
 fi
